

name: 'ecommerce_dbt'
version: '1.0.0'

profile: 'ecommerce_dbt'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


seeds:
  ecommerce_dbt:
    +schema: raw            # semua CSV masuk ke schema "raw"
    +quote_columns: false

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  ecommerce_dbt:
    +materialized: view     # default (hemat storage)
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
